env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - plugin:react/jsx-runtime
  - plugin:storybook/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
  - eslint-plugin-storybook
"rules": {
  "quotes": ["error", "double"],
  "react/function-component-definition": [0],
  "import/extensions": [0],
  "import/no-unresolved": [0],
  "react/jsx-filename-extension": [0],
  "react/require-default-props": [0],
  "react/jsx-props-no-spreading": [0],
}
